version: "3" 
services:
  web_firstblogwsl:
    image: alexrogna/firstblogwsl_web:prod
    expose:
      - 3000
    env_file:
      - .env/production/database_firstblogwsl
      - .env/production/web_firstblogwsl
    environment:
      - VIRTUAL_HOST=firstblogwsl.alexrogna.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=firstblogwsl.alexrogna.com
    networks:
      - proxy
    restart: always

  database_firstblogwsl:
    image: postgres
    env_file:
      - .env/production/database_firstblogwsl
    volumes:
      - db_data_firstblogwsl:/var/lib/postgresql/data
    networks:
      - proxy
    restart: always
    
  db-migrator_firstblogwsl:
    image: alexrogna/firstblogwsl_web:prod
    command: ["./wait-for", "--timeout=300", "database_firstblogwsl:5432", "--", "bin/rails", "db:create" , "db:migrate"]
    env_file:
      - .env/production/database_firstblogwsl
      - .env/production/web_firstblogwsl
    networks:
      - proxy
volumes:
  db_data_firstblogwsl:
networks:
  proxy: